### ISSUE TITLE
Seperate behavior for `.` and `[]`

### ISSUE THREAD

**Issue by Evgenus** [kennknowles/python-jsonpath-rw#46]
I'd like to use jsonpath for matching python objects structure. So the way I see is to create `Child` override in parser. But I don't want to overload entire function https://github.com/kennknowles/python-jsonpath-rw/blob/master/jsonpath_rw/parser.py#L71-L88 Maybe It is good idea to split it into separate methods for each rule?

**Comment by kennknowles** [comment]
It is JSONPath spec that these are the same, as far as JSON goes.

But in fact, preliminary versions of this library supported object fields as well as dictionary entries, since there is no rule that JSON has to be deserialized into dicts and lists, etc. The trouble is that there are ambiguous cases where it is not clearly right to do one or the other.

I am open to ideas. A couple that come to mind:

 - Global configuration as to whether you want to query into objects or dicts+lists
 - Add a new backtick operator like \`field\` (or even aliased to `f`) that either gets one field, or switches behavior for a whole sub-JSONpath expression.

**Comment by Evgenus** [comment]
I hope that would not abuse you. I'm trying to get such functionality from any of mature query-libraries. I've described use case here https://github.com/adriank/ObjectPath/issues/50
